# theme: jekyll-theme-dinky
title: BIA Framework
remote_theme: pmarsceill/just-the-docs
logo: "/docs/Images/BIALogo.gif"
aux_links:
  "Live demo":
    - "https://biateam.github.io/BIADocs/App/Index.html"
color_scheme: dark