theme: jekyll-theme-dinky
title: BIA Framework
description: The BIA Framework is a set of components. It give the possibility to build quickly a modern application at the state of art in 2021 (Green IT, Secure, Structured, RWD, Ergonomic, Fast, Powerful, Open to web component integration) * [Prerequisite for development](./PREREQUISITE.md)
